site_name: Backstage Docs Test
description: |
  Testing TechDocs
repo_url: https://github.com/realandersn/backstage-docs-test/
edit_uri: edit/master/docs/

nav:
  - Introduction: ./
  - Sub section:
      - Another page: another_page.md
      - Yet another page: yet_another_page.md

plugins:
  - techdocs-core

theme:
  name: material
  features:
    - navigation.expand
