site_name: Backstage Docs Test
description: Testing TechDocs
repo_url: https://github.com/realandersn/backstage-docs-test/

nav:
  - Introduction: README.md
  - Sub section:
      - Another page: another_page.md
      - Yet another page: yet_another_page.md

plugins:
  - techdocs-core

theme:
  name: mkdocs-material
  features:
    - navigation.expand
