site_name: Backstage Docs Test
description: Testing TechDocs
repo_url: https://github.com/realandersn/backstage-docs-test/

nav:
  - Introduction: README.md
  - Another page: another_page.md

plugins:
  - techdocs-core
