site_name: Backstage Docs Test
description: |
  Testing TechDocs
repo_url: https://github.com/realandersn/backstage-docs-test/
edit_uri: edit/master/docs/

nav:
  - Introduction: ./
  - Sub section:
      - Another page: another_page.md
      - Yet another page: yet_another_page.md
  - Test: test.md
  - Feature test:
      - Intro to Formatting TechDocs: features/introduction.md
      - Headings: features/headings.md
      - Linking: features/linking.md
      - Images: features/images.md
      - Code snippets: features/code-snippets.md
      - Variables: features/variables.md
      - Notes, tips, info, and warnings: features/call-outs.md
      - Dropdowns: features/dropdowns.md
      - Tables: features/tables.md
      - Tabs: features/grouping.md
      - Abbreviations: features/abbreviations.md
      - LaTeX math equations: features/equations.md
      - Graphviz: features/graphviz.md
      - PlantUML: features/plantuml.md
      - Mermaid: features/mermaid.md
      - List Formatting: features/list-format.md
      - Embedding content: features/embedding-content.md
      - Embedding code: features/embedding-code.md
      - File downloads: features/file-downloads.md
      - features/footnotes.md

plugins:
  - techdocs-core

theme:
  name: material
  features:
    - navigation.expand
